##########
# HEADER #
##########
header:
  version: 20
  includes:
    - includes/rauc.yaml

############
# DEFAULTS #
############
defaults:
  repos:
    branch: scarthgap

##################
# REPOS & LAYERS #
##################
repos:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    path: "sources/poky"
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: "git://git.openembedded.org/meta-openembedded"
    path: "sources/meta-openembedded"
    layers:
      meta-oe:
      meta-filesystems:
      meta-networking:
      meta-python:

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    path: "sources/meta-arm"
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-virtualization:
    url: "git://git.yoctoproject.org/meta-virtualization"
    path: "sources/meta-virtualization"

  meta-autonomos:
    layers:
      meta-autonomos-core:
